# Generated by Django 4.0.2 on 2022-02-09 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retencion', '0001_initial'),
        ('cedoc', '0001_initial'),
        ('etiqueta', '0001_initial'),
        ('mrd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('code', models.CharField(help_text='referencia para el cliente', max_length=250, null=True, verbose_name='código / número')),
                ('rc', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='RC')),
                ('Serie_de', models.CharField(max_length=150, verbose_name='Serie de:')),
                ('Serie_hasta', models.CharField(max_length=150, verbose_name='Serie hasta:')),
                ('Mes_de', models.CharField(choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, verbose_name='Mes de:')),
                ('Mes_hasta', models.CharField(choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, verbose_name='Mes hasta:')),
                ('year_de', models.CharField(choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, verbose_name='Año de')),
                ('year_hasta', models.CharField(choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, verbose_name='Año hasta')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('status', models.CharField(choices=[('Pre add', 'Pre Agregado'), ('IN', 'En custodia'), ('OUT', 'Fuera de custodia'), ('DELETE', 'Baja'), ('DESTROYED', 'Destruido')], default='Pre Agregado', max_length=10, verbose_name='Estatus')),
                ('files', models.IntegerField(blank=True, null=True)),
                ('seguridad', models.CharField(choices=[('P', 'Publico'), ('I', 'Interno'), ('C', 'Confidencial')], default='Interno', max_length=10, verbose_name='Nivel de Seguridad')),
                ('template_data', models.CharField(blank=True, max_length=10000, null=True, verbose_name='datos de la etiqueta')),
                ('last_out_order', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'Caja',
                'ordering': ['rc'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('rc', models.BigIntegerField(unique=True, verbose_name='RC Folder')),
                ('code', models.CharField(help_text='referencia para el cliente', max_length=250, null=True, verbose_name='código / número')),
                ('Serie_de', models.CharField(max_length=150, verbose_name='Serie de:')),
                ('Serie_hasta', models.CharField(max_length=150, verbose_name='Serie hasta:')),
                ('Mes_de', models.CharField(choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, verbose_name='Mes de:')),
                ('Mes_hasta', models.CharField(choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, verbose_name='Mes hasta:')),
                ('year_de', models.CharField(choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, verbose_name='Año de')),
                ('year_hasta', models.CharField(choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, verbose_name='Año hasta')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('status', models.CharField(choices=[('Pre add', 'Pre Agregado'), ('IN', 'En custodia'), ('OUT', 'Fuera de custodia'), ('DELETE', 'Baja'), ('DESTROYED', 'Destruido')], default='En Custodia', max_length=10, verbose_name='Estatus')),
                ('seguridad', models.CharField(choices=[('P', 'Publico'), ('I', 'Interno'), ('C', 'Confidencial')], default='Interno', max_length=10, verbose_name='Nivel de Seguridad')),
                ('template_data', models.CharField(blank=True, max_length=10000, null=True)),
                ('last_out_order', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area el cual pertenece')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedoc.bodega', verbose_name='Bodega')),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Tipo de proceso')),
                ('Retencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retencion.retencion', verbose_name='Retencion')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede el Cual pertenece')),
                ('Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.serie', verbose_name='Serie')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.caja', verbose_name='RC Caja')),
                ('sub_Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_serie', verbose_name='Sub serie')),
                ('sub_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Dcoumento')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiqueta.formfile')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Tipo de Dcoumento')),
            ],
            options={
                'verbose_name': 'Folder',
                'verbose_name_plural': 'Folders',
                'db_table': 'Folder',
                'ordering': ('rc',),
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, max_length=300, null=True, verbose_name='Descripcion')),
                ('rc', models.BigIntegerField(unique=True, verbose_name='RC documento')),
                ('Serie_de', models.CharField(max_length=150, verbose_name='Serie de:')),
                ('Serie_hasta', models.CharField(max_length=150, verbose_name='Serie hasta:')),
                ('Mes_de', models.CharField(choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, verbose_name='Mes de:')),
                ('year_de', models.CharField(choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, verbose_name='Año de')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='Archivos')),
                ('status', models.CharField(choices=[('Pre add', 'Pre Agregado'), ('IN', 'En custodia'), ('OUT', 'Fuera de custodia'), ('DELETE', 'Baja'), ('DESTROYED', 'Destruido')], default='En Custodia', max_length=10, verbose_name='Estatus')),
                ('template_data', models.CharField(blank=True, max_length=10000, null=True)),
                ('seguridad', models.CharField(choices=[('P', 'Publico'), ('I', 'Interno'), ('C', 'Confidencial')], default='Interno', max_length=10, verbose_name='Nivel de Seguridad')),
                ('scan_date', models.DateTimeField(blank=True, null=True)),
                ('index_date', models.DateTimeField(blank=True, null=True)),
                ('scan_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('index_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deleted_pages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area el cual pertenece')),
                ('Location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedoc.bodega', verbose_name='Bodega')),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Tipo de proceso')),
                ('Retencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retencion.retencion', verbose_name='Retencion')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede el Cual pertenece')),
                ('Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.serie', verbose_name='Serie')),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.caja', verbose_name='RC Caja')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.folder', verbose_name='RC folder')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'db_table': 'Documento',
                'ordering': ['id'],
            },
        ),
    ]
