# Generated by Django 4.0.2 on 2022-02-09 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('mrd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('retencion', '0001_initial'),
        ('etiqueta', '0001_initial'),
        ('cedoc', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='index_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='sub_Serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_serie', verbose_name='Sub serie'),
        ),
        migrations.AddField(
            model_name='document',
            name='sub_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Dcoumento'),
        ),
        migrations.AddField(
            model_name='document',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiqueta.formdoc'),
        ),
        migrations.AddField(
            model_name='document',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Tipo de Dcoumento'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area el cual pertenece'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedoc.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Tipo de proceso'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Retencion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retencion.retencion', verbose_name='Retencion'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede el Cual pertenece'),
        ),
        migrations.AddField(
            model_name='caja',
            name='Serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.serie', verbose_name='Serie'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sub_Serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_serie', verbose_name='Sub serie'),
        ),
        migrations.AddField(
            model_name='caja',
            name='sub_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Dcoumento'),
        ),
        migrations.AddField(
            model_name='caja',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiqueta.formbox', verbose_name='tipo de etiqueta'),
        ),
        migrations.AddField(
            model_name='caja',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Tipo de Dcoumento'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('rc', 'Sede')},
        ),
    ]
