# Generated by Django 4.0.2 on 2022-02-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='deleted_pages',
        ),
        migrations.RemoveField(
            model_name='document',
            name='index_pages',
        ),
        migrations.RemoveField(
            model_name='document',
            name='scan_pages',
        ),
    ]
