# Generated by Django 4.0.2 on 2022-02-11 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etiqueta', '0001_initial'),
        ('retencion', '0002_alter_retencion_tim_dos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrd', '0001_initial'),
        ('inventario', '0004_remove_document_serie_hasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='Mes_de',
            field=models.CharField(blank=True, choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, null=True, verbose_name='Mes de:'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Mes_hasta',
            field=models.CharField(blank=True, choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, null=True, verbose_name='Mes hasta:'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retencion.retencion', verbose_name='Retencion'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Serie_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie de:'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='Serie_hasta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie hasta:'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='sub_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Dcoumento'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiqueta.formbox', verbose_name='tipo de etiqueta'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='year_de',
            field=models.CharField(blank=True, choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, null=True, verbose_name='Año de'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='year_hasta',
            field=models.CharField(blank=True, choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, null=True, verbose_name='Año hasta'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Mes_de',
            field=models.CharField(blank=True, choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, null=True, verbose_name='Mes de:'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retencion.retencion', verbose_name='Retencion'),
        ),
        migrations.AlterField(
            model_name='document',
            name='Serie_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie de:'),
        ),
        migrations.AlterField(
            model_name='document',
            name='index_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Indexado'),
        ),
        migrations.AlterField(
            model_name='document',
            name='index_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que indexa'),
        ),
        migrations.AlterField(
            model_name='document',
            name='scan_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Escaneo'),
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiqueta.formdoc'),
        ),
        migrations.AlterField(
            model_name='document',
            name='year_de',
            field=models.CharField(blank=True, choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, null=True, verbose_name='Año de'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='Mes_de',
            field=models.CharField(blank=True, choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, null=True, verbose_name='Mes de:'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='Mes_hasta',
            field=models.CharField(blank=True, choices=[['ENERO', 'Enero'], ['FEBRERO', 'Febrero'], ['MARZO', 'Marzo'], ['ABRIL', 'Abril'], ['MAYO', 'Mayo'], ['JUNIO', 'Junio'], ['JULIO', 'Julio'], ['AGOSTO', 'Agosto'], ['SEPTIEMBRE', 'Septiembre'], ['OCTUBRE', 'Octubre'], ['NOVIEMBRE', 'Noviembre'], ['DICIEMBRE', 'Diciembre']], max_length=20, null=True, verbose_name='Mes hasta:'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='Retencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retencion.retencion', verbose_name='Retencion'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='Serie_de',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie de:'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='Serie_hasta',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Serie hasta:'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='sub_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Dcoumento'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='etiqueta.formfile'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='year_de',
            field=models.CharField(blank=True, choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, null=True, verbose_name='Año de'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='year_hasta',
            field=models.CharField(blank=True, choices=[['2010', '2010'], ['2011', '2011'], ['2012', '2012'], ['2013', '2013'], ['2014', '2014'], ['2015', '2015'], ['2016', '2016'], ['2017', '2017'], ['2018', '2018'], ['2019', '2019'], ['2020', '2020'], ['2021', '2021'], ['2022', '2022']], max_length=5, null=True, verbose_name='Año hasta'),
        ),
    ]
