# Generated by Django 4.0.2 on 2022-02-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_remove_caja_end_date_remove_caja_last_out_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='seguridad',
            field=models.CharField(choices=[('P', 'Publico'), ('I', 'Interno'), ('C', 'Confidencial')], default='Interno', max_length=15, verbose_name='Nivel de Seguridad'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='status',
            field=models.CharField(choices=[('Pre add', 'Pre Agregado'), ('IN', 'En custodia'), ('OUT', 'Fuera de custodia'), ('DELETE', 'Baja'), ('DESTROYED', 'Destruido')], default='Pre Agregado', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='document',
            name='seguridad',
            field=models.CharField(choices=[('P', 'Publico'), ('I', 'Interno'), ('C', 'Confidencial')], default='Interno', max_length=15, verbose_name='Nivel de Seguridad'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('Pre add', 'Pre Agregado'), ('IN', 'En custodia'), ('OUT', 'Fuera de custodia'), ('DELETE', 'Baja'), ('DESTROYED', 'Destruido')], default='En Custodia', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='seguridad',
            field=models.CharField(choices=[('P', 'Publico'), ('I', 'Interno'), ('C', 'Confidencial')], default='Interno', max_length=15, verbose_name='Nivel de Seguridad'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='status',
            field=models.CharField(choices=[('Pre add', 'Pre Agregado'), ('IN', 'En custodia'), ('OUT', 'Fuera de custodia'), ('DELETE', 'Baja'), ('DESTROYED', 'Destruido')], default='En Custodia', max_length=15, verbose_name='Estatus'),
        ),
    ]
