# Generated by Django 4.0.2 on 2022-02-11 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_alter_caja_seguridad_alter_caja_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='rc',
            field=models.BigIntegerField(default=2, unique=True, verbose_name='RC'),
            preserve_default=False,
        ),
    ]
