# Generated by Django 4.0.2 on 2022-02-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_alter_caja_rc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='caja',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.caja', verbose_name='RC Caja'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inventario.folder', verbose_name='RC folder'),
            preserve_default=False,
        ),
    ]
