# Generated by Django 4.0.2 on 2022-02-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_document_caja_alter_document_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['rc'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
