# Generated by Django 4.0.2 on 2022-02-11 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0002_alter_area_name_alter_proceso_name_alter_serie_name_and_more'),
        ('inventario', '0010_alter_document_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='sub_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='sub_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='sub_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Tipo de Documento'),
        ),
    ]
