# Generated by Django 4.0.2 on 2022-02-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_alter_caja_sub_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='Sopo',
            field=models.CharField(choices=[('D', 'Digital'), ('DG', 'Digitalizado'), ('F', 'Fisico')], default='Interno', max_length=15, verbose_name='Soporte'),
        ),
        migrations.AddField(
            model_name='caja',
            name='fun',
            field=models.CharField(choices=[('F', 'Facilitativos'), ('FC', 'Facultativos'), ('C', 'Sustantivos')], default='Interno', max_length=15, verbose_name='Funciones'),
        ),
        migrations.AddField(
            model_name='caja',
            name='ord',
            field=models.CharField(choices=[('C', 'Cronologico'), ('N', 'Numerico'), ('AF', 'Alfabetico')], default='Interno', max_length=15, verbose_name='Ordenacion'),
        ),
        migrations.AddField(
            model_name='document',
            name='Sopo',
            field=models.CharField(choices=[('D', 'Digital'), ('DG', 'Digitalizado'), ('F', 'Fisico')], default='Interno', max_length=15, verbose_name='Soporte'),
        ),
        migrations.AddField(
            model_name='document',
            name='fun',
            field=models.CharField(choices=[('F', 'Facilitativos'), ('FC', 'Facultativos'), ('C', 'Sustantivos')], default='Interno', max_length=15, verbose_name='Funciones'),
        ),
        migrations.AddField(
            model_name='document',
            name='ord',
            field=models.CharField(choices=[('C', 'Cronologico'), ('N', 'Numerico'), ('AF', 'Alfabetico')], default='Interno', max_length=15, verbose_name='Ordenacion'),
        ),
        migrations.AddField(
            model_name='folder',
            name='Sopo',
            field=models.CharField(choices=[('D', 'Digital'), ('DG', 'Digitalizado'), ('F', 'Fisico')], default='Interno', max_length=15, verbose_name='Soporte'),
        ),
        migrations.AddField(
            model_name='folder',
            name='fun',
            field=models.CharField(choices=[('F', 'Facilitativos'), ('FC', 'Facultativos'), ('C', 'Sustantivos')], default='Interno', max_length=15, verbose_name='Funciones'),
        ),
        migrations.AddField(
            model_name='folder',
            name='ord',
            field=models.CharField(choices=[('C', 'Cronologico'), ('N', 'Numerico'), ('AF', 'Alfabetico')], default='Interno', max_length=15, verbose_name='Ordenacion'),
        ),
    ]
