# Generated by Django 4.0.2 on 2022-02-11 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_caja_sopo_caja_fun_caja_ord_document_sopo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='document',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripcion'),
        ),
    ]
