# Generated by Django 4.0.2 on 2022-02-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_caja_last_out_order_caja_template_caja_template_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='media_file',
            new_name='mediafile',
        ),
    ]
