# Generated by Django 4.0.2 on 2022-02-17 22:23

import django.core.files.storage
from django.db import migrations, models
import inventario.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_rename_media_file_document_mediafile'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='media_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location='D:\\PROJECT\\inventario\\app\\media'), upload_to=inventario.models.get_media_path),
        ),
    ]
