# Generated by Django 4.0.2 on 2022-02-09 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del Area')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo de Area')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'db_table': 'Area',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo ')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area Cual pertenece')),
            ],
            options={
                'verbose_name': 'Proceso',
                'verbose_name_plural': 'Procesos',
                'db_table': 'Proceso',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo de la Sede')),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Nombre de la Sede')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'Sede',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Serie')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo de la Serie')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area al que pertenece')),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Proceso')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede de la que pertenece')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'db_table': 'Serie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='sub_Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la Sub Serie')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo de la Sub Serie')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area al que pertenece')),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Proceso')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede de la que pertenece')),
                ('Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.serie', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'sub Serie',
                'verbose_name_plural': 'sub Series',
                'db_table': 'sub_Serie',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre tipo documento')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo de tipo documento')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area al que pertenece')),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Proceso')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede de la que pertenece')),
                ('Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.serie', verbose_name='Serie')),
                ('sub_Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_serie', verbose_name='Sub Serie')),
            ],
            options={
                'verbose_name': 'tipo documento',
                'verbose_name_plural': 'tipo documento',
                'db_table': 'tipo_documento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='sub_tipo_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Fecha de Creacion')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualizacion')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre sub tipo documento')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Codigo de sub tipo documento')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('Area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area al que pertenece')),
                ('Proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Proceso')),
                ('Sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede de la que pertenece')),
                ('Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.serie', verbose_name='Serie')),
                ('sub_Serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sub_serie', verbose_name='Sub Serie')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Nombre tipo documento')),
            ],
            options={
                'verbose_name': 'Sub tipo documento',
                'verbose_name_plural': 'Sub tipos de documentos',
                'db_table': 'sub_tipo_documento',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='proceso',
            name='Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede de la que pertenece'),
        ),
        migrations.AddField(
            model_name='area',
            name='Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede Cual pertenece'),
        ),
    ]
