# Generated by Django 4.0.2 on 2022-02-11 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre del Area'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre de la Serie'),
        ),
        migrations.AlterField(
            model_name='sub_serie',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre de la Sub Serie'),
        ),
        migrations.AlterField(
            model_name='sub_tipo_documento',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre sub tipo documento'),
        ),
        migrations.AlterField(
            model_name='tipo_documento',
            name='name',
            field=models.CharField(max_length=300, unique=True, verbose_name='Nombre tipo documento'),
        ),
    ]
