# Generated by Django 4.0.2 on 2022-02-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0002_alter_area_name_alter_proceso_name_alter_serie_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='Sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede Cual pertenece'),
        ),
    ]
