# Generated by Django 4.0.2 on 2022-02-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0003_alter_proceso_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='Sede',
        ),
    ]
