# Generated by Django 4.0.2 on 2022-02-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0004_remove_proceso_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='Sede',
        ),
    ]
