# Generated by Django 4.0.2 on 2022-02-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0006_remove_sub_serie_area_remove_sub_serie_proceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='Area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area al que pertenece'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serie',
            name='Sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede de la que pertenece'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_serie',
            name='Area',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='mrd.area', verbose_name='Area al que pertenece'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_serie',
            name='Proceso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrd.proceso', verbose_name='Proceso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sub_serie',
            name='Sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede de la que pertenece'),
            preserve_default=False,
        ),
    ]
