# Generated by Django 4.0.2 on 2022-02-18 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0008_proceso_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_serie',
            name='Proceso',
        ),
    ]
