# Generated by Django 4.0.2 on 2022-02-09 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código')),
                ('active_years', models.PositiveSmallIntegerField(default=10, verbose_name='Años estado activo')),
                ('active_months', models.PositiveSmallIntegerField(default=120, verbose_name='Meses estado activo')),
                ('semiactive_years', models.PositiveSmallIntegerField(default=2, verbose_name='Años estado semi-activo')),
                ('semiactive_months', models.PositiveSmallIntegerField(default=24, verbose_name='Meses estado semi-activo')),
            ],
            options={
                'verbose_name': 'record serie',
                'verbose_name_plural': 'Etiqueta - cajas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código')),
                ('active_years', models.PositiveSmallIntegerField(default=10, verbose_name='Años estado activo')),
                ('active_months', models.PositiveSmallIntegerField(default=120, verbose_name='Meses estado activo')),
                ('semiactive_years', models.PositiveSmallIntegerField(default=2, verbose_name='Años estado semi-activo')),
                ('semiactive_months', models.PositiveSmallIntegerField(default=24, verbose_name='Meses estado semi-activo')),
            ],
            options={
                'verbose_name': 'record serie',
                'verbose_name_plural': 'Etqiueta - Documentos',
            },
        ),
        migrations.CreateModel(
            name='FormFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código')),
                ('active_years', models.PositiveSmallIntegerField(default=10, verbose_name='Años estado activo')),
                ('active_months', models.PositiveSmallIntegerField(default=120, verbose_name='Meses estado activo')),
                ('semiactive_years', models.PositiveSmallIntegerField(default=2, verbose_name='Años estado semi-activo')),
                ('semiactive_months', models.PositiveSmallIntegerField(default=24, verbose_name='Meses estado semi-activo')),
            ],
            options={
                'verbose_name': 'record serie',
                'verbose_name_plural': 'Etiquetas folder',
            },
        ),
        migrations.CreateModel(
            name='FieldFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('name', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('field', models.CharField(choices=[('input', 'Input'), ('textarea', 'Textarea')], max_length=10, null=True)),
                ('show', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiqueta.formfile')),
            ],
            options={
                'verbose_name': 'campo',
                'verbose_name_plural': 'campos disponibles',
            },
        ),
        migrations.CreateModel(
            name='FieldDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('name', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('field', models.CharField(choices=[('input', 'Input'), ('textarea', 'Textarea')], max_length=10, null=True)),
                ('show', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiqueta.formdoc')),
            ],
            options={
                'verbose_name': 'campo',
                'verbose_name_plural': 'campos disponibles',
            },
        ),
        migrations.CreateModel(
            name='FieldBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(null=True, verbose_name='Position')),
                ('name', models.CharField(max_length=255, null=True)),
                ('label', models.CharField(max_length=255, null=True)),
                ('field', models.CharField(choices=[('input', 'Input'), ('textarea', 'Textarea')], max_length=10, null=True)),
                ('show', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiqueta.formbox')),
            ],
            options={
                'verbose_name': 'campo',
                'verbose_name_plural': 'campos disponibles',
                'ordering': ['name'],
            },
        ),
    ]
