# Generated by Django 4.0.2 on 2022-02-16 22:37

from django.db import migrations
import mrd.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Documento',
            field=mrd.models.MultiSelectField(blank=True, choices=[('', 'Aún no hay Documentos definidos')], max_length=10000, null=True, verbose_name='Tipos de Documentos'),
        ),
    ]
