# Generated by Django 4.0.2 on 2022-02-16 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0003_alter_proceso_sede'),
        ('user', '0006_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrd.tipo_documento', verbose_name='Nombre tipo documento'),
        ),
    ]
