# Generated by Django 4.0.2 on 2022-02-16 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Documento',
        ),
    ]
