# Generated by Django 4.0.2 on 2022-02-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrd', '0010_sub_serie_proceso'),
        ('user', '0008_remove_user_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrd.sede', verbose_name='Sede'),
        ),
    ]
