# Generated by Django 4.0.2 on 2022-02-21 16:54

from django.db import migrations
import mrd.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_sede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Area',
            field=mrd.models.MultiSelectField(blank=True, choices=[('', 'Aún no hay Areas definida')], max_length=10000, null=True, verbose_name='Area'),
        ),
    ]
