# Generated by Django 4.0.2 on 2022-02-09 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Disposicion Final',
                'verbose_name_plural': 'Disposiciones',
                'db_table': 'disposicion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('disposicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='retencion.disposicion', verbose_name='Disposicion Final')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'procedimiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_uno', models.CharField(choices=[['OF', 'OFICINA'], ['ARC', 'Archivo Central'], ['LG', 'Logicsa']], max_length=150, verbose_name='Resguardo uno')),
                ('tim_uno', models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10']], max_length=150, verbose_name='Años del Resguardo uno')),
                ('res_dos', models.CharField(choices=[['OF', 'OFICINA'], ['ARC', 'Archivo Central'], ['LG', 'Logicsa']], max_length=150, verbose_name='Resguardo Dos')),
                ('tim_dos', models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10']], max_length=150, verbose_name='AÑOS del Resguardo Dos')),
                ('res_tres', models.CharField(choices=[['OF', 'OFICINA'], ['ARC', 'Archivo Central'], ['LG', 'Logicsa']], max_length=150, verbose_name='Resguardo Tres')),
                ('tim_tres', models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10']], max_length=150, verbose_name='Años del Resguardo Tres')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('Serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrd.serie', verbose_name='Serie')),
                ('disposicion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retencion.disposicion', verbose_name='Disposicion Final')),
                ('procedimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='retencion.procedimiento', verbose_name='Procedimiento')),
                ('sub_Serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrd.sub_serie', verbose_name='Sub Serie')),
                ('sub_tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrd.sub_tipo_documento', verbose_name='Sub Tipo de Documento')),
                ('tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrd.tipo_documento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Retencion',
                'verbose_name_plural': 'Retenciones',
                'db_table': 'Retencion',
                'ordering': ['id'],
            },
        ),
    ]
