# Generated by Django 4.0.2 on 2022-02-11 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retencion',
            name='tim_dos',
            field=models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6'], ['7', '7'], ['8', '8'], ['9', '9'], ['10', '10']], max_length=150, verbose_name='Años del Resguardo Dos'),
        ),
    ]
