# Generated by Django 4.0.2 on 2022-02-09 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='Codigo')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nombre')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro')),
                ('Sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrd.sede', verbose_name='Sede')),
            ],
            options={
                'verbose_name': 'Orden de trabajo',
                'verbose_name_plural': 'Ordenes de trabajo',
                'db_table': 'ordenes',
                'ordering': ['id'],
            },
        ),
    ]
